#!/usr/bin/env sh
BASE_DIR=$(pwd $(dirname ${BASH_SOURCE[0]})/../)
GIT_URL=gitee.com:zhengqbbb/x-cmd-official-template.git
BRANCH_NAME=gh-page

d() {
    set -e

    yarn docs:build
    cd $BASE_DIR/docs/.vuepress/dist
    # 如果是发布到自定义域名
    # echo 'www.x-cmd.com' > CNAME
    git init
    git remote add origin git@$GIT_URL
    git checkout -b $BRANCH_NAME
    git add -A
    git commit -m 'deploy'
    git push -f git@$GIT_URL $BRANCH_NAME

    cd -
}


i() {
    if [ ! -d "$BASE_DIR/node_modules" ]; then
      x i &&
      d
    else
      d
    fi
}

i